name: HCL OneTest Server

on: workflow_dispatch

jobs:
    OTS-Action:
        runs-on: self-hosted
        name: HCL OneTest Server
        steps:
         - name: Execute Test
           uses: HCL-TECH-SOFTWARE/onetest-server-action@main
           with:
            serverUrl: https://10.134.59.190.nip.io
            offlineToken: eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIwYjJiMzcyMy04YWNlLTQzNTYtYmIyZi1kOTMwYzkwZWNmZDkifQ.eyJpYXQiOjE2OTMxOTc5MjUsImp0aSI6IjI1NmZiMzBhLWMyMzYtNDhlYy1iY2QyLWFlYTE1YWY4NTcxNCIsImlzcyI6Imh0dHBzOi8vMTAuMTM0LjU5LjE5MC5uaXAuaW8vYXV0aC9yZWFsbXMvdGVzdHNlcnZlciIsImF1ZCI6Imh0dHBzOi8vMTAuMTM0LjU5LjE5MC5uaXAuaW8vYXV0aC9yZWFsbXMvdGVzdHNlcnZlciIsInN1YiI6IjM0NDRkNWMyLWM0Y2ItNDdlZS1iZDJmLTdmZjI2NDFlYmJlMiIsInR5cCI6Ik9mZmxpbmUiLCJhenAiOiJ0ZXN0c2VydmVyIiwic2Vzc2lvbl9zdGF0ZSI6ImNiYzA4ZGE0LWI2NzMtNGJlYy1iMmQwLWVlNDI3NmFiYTNjNCIsInNjb3BlIjoib2ZmbGluZV9hY2Nlc3MgZW1haWwgcHJvZmlsZSIsInNpZCI6ImNiYzA4ZGE0LWI2NzMtNGJlYy1iMmQwLWVlNDI3NmFiYTNjNCJ9.dRN6nyzv7IyyBaDK4m8LIt8pZddxLfQE3BfseS5GbCQ
            teamspace: Initial Team Space
            project: PTSVT
            branch: Alice_1052
            assetId: 2b596f5a-4c56-4572-996f-5a4c5675727a
