name: Rational Test Automation Server

on: workflow_dispatch

jobs:
    OTS-Action:
        runs-on: self-hosted
        name: Rational Test Automation Server
        steps:
         - name: Execute Test
           uses: IBM/devopsauto-testserver-actions@main
           with:
            serverUrl: https://10.134.59.236.nip.io
            offlineToken: eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIzNTg2MTQwOC1kMjJmLTQ0MjUtODdiOC0yMWY2YjI5MzBmMjQifQ.eyJpYXQiOjE2ODQ4NTMxNTgsImp0aSI6ImEwOGU5MzEyLWEzNmQtNDIxOC05ZDc2LTMyMGQ0NTBjNzE0MCIsImlzcyI6Imh0dHBzOi8vMTAuMTM0LjU5LjIzNi5uaXAuaW8vYXV0aC9yZWFsbXMvdGVzdHNlcnZlciIsImF1ZCI6Imh0dHBzOi8vMTAuMTM0LjU5LjIzNi5uaXAuaW8vYXV0aC9yZWFsbXMvdGVzdHNlcnZlciIsInN1YiI6IjNlZWVlMTMzLWFjYTEtNDI0Yi1hZjhhLWJjMGUyZGE2NGI0OCIsInR5cCI6Ik9mZmxpbmUiLCJhenAiOiJ0ZXN0c2VydmVyIiwic2Vzc2lvbl9zdGF0ZSI6IjBjZGQ5ZTNhLTQ0ZTUtNDgzMi04MWUzLTZkMjRkMWZkYTljNyIsInNjb3BlIjoidGVzdHNlcnZlciBlbWFpbCBvZmZsaW5lX2FjY2VzcyBwcm9maWxlIiwic2lkIjoiMGNkZDllM2EtNDRlNS00ODMyLTgxZTMtNmQyNGQxZmRhOWM3In0.JwrQQi3SPjM3TRvps_JEmMNV0A96SCtubJoraz6ABUU
            teamspace: Initial Team Space
            project: AliceSVT
            branch: master
            assetId: 1634fbf5-d6ff-444c-b4fb-f5d6ff944c76
