name: Rational Performance Tester

on: workflow_dispatch

jobs:
    Performance-Action:
        name: Rational Performance Tester
        runs-on: self-hosted
        steps:
         - name: Rational Performance Tester
           uses: IBM/devopsauto-perftest-actions@main
           with:
            workspace: C:\PTWsps\1053Demo
            project: CmdlineV2Prj_1
            suite: sch5.testsuite
