name: Rational Performance Tester

on: workflow_dispatch

jobs:
    Performance-Action:
        name: Rational Performance Tester
        runs-on: self-hosted
        steps:
         - name: Rational Performance Tester
           uses: IBM/devopsauto-perftest-actions@main
           with:
            workspace: /Users/alicesebastian/HCL/hclonetest/workspace1054_RPT
            project: CmdlineV2
            suite: 021023_Sched_1.testsuite
