name: Rational Performance Tester

on: workflow_dispatch

jobs:
    Performance-Action:
        name: Rational Performance Tester
        runs-on: self-hosted
        steps:
         - name: Rational Performance Tester
           uses: IBM/devopsauto-perftest-actions@main
           with:
            workspace: /Users/alicesebastian/IBM/rationalsdp/workspace1053
            project: Regression1021_SchName_Brotlii
            suite: Schedules/Schd102_Customcode.testsuite
